<a href="https://colab.research.google.com/github/Shanthan0/Neural-Networks-and-Deep-Learning-Coursework/blob/main/ICP_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. Create a class Employee and then do the following

*   Create a data member to count the number of Employees
*   Create a constructor to initialize name, family, salary, department
*   Create a function to average salary
*   Create a Fulltime Employee class and it should inherit the properties of
    Employee class

2. Create a Fulltime Employee class and it should inherit the properties of Employee class

In [15]:
class Employee:

    count = 0

    def __init__(self, name, family, salary, department):

        self.name = name
        self.family = family
        self.salary = salary
        self.department = department
        Employee.count += 1

    def get_full_name(self):
        return f"{self.name} {self.family}"

    def average_salary(employees):
        if not employees:
            return 0

        total_salary = sum(emp.salary for emp in employees)
        return total_salary / len(employees)

class FullTimeEmployee(Employee):
    def __init__(self, name, family, salary, department):
        super().__init__(name, family, salary, department)


emp1 = Employee("Sree", "Kuthuru", 50000, "Data")
emp2 = FullTimeEmployee("Kargill", "Kane", 65000, "DevOps")

print(emp1.get_full_name())
print(emp2.get_full_name())
print(Employee.count)
print(Employee.average_salary([emp1, emp2]))


Sree Kuthuru
Kargill Kane
2
57500.0


Using NumPy create random vector of size 20 having only float in the range 1-20.

*   Then reshape the array to 4 by 5
*   Then replace the max in each row by 0 (axis=1)

In [11]:
import numpy as np

vector = np.random.uniform(low=1, high=20, size=20)
print('Original Vector:\n',vector)
reshaped_vector = vector.reshape(4, 5)
print("Reshaped Vector:\n", reshaped_vector)
reshaped_vector[np.arange(reshaped_vector.shape[0]), reshaped_vector.argmax(axis=1)] = 0
print("Updated Vector:\n", reshaped_vector)


Original Vector:
 [ 6.01917511 11.77514003  8.81033408  5.16445298 16.91918412 15.44626079
 11.56342674 10.88847749 10.71264868 12.14344594 19.09676928  5.17869182
  4.51452191 12.8031804  12.27019776 18.46375142 13.53967468 19.80417844
 11.9261086  10.33819861]
Reshaped Vector:
 [[ 6.01917511 11.77514003  8.81033408  5.16445298 16.91918412]
 [15.44626079 11.56342674 10.88847749 10.71264868 12.14344594]
 [19.09676928  5.17869182  4.51452191 12.8031804  12.27019776]
 [18.46375142 13.53967468 19.80417844 11.9261086  10.33819861]]
Updated Vector:
 [[ 6.01917511 11.77514003  8.81033408  5.16445298  0.        ]
 [ 0.         11.56342674 10.88847749 10.71264868 12.14344594]
 [ 0.          5.17869182  4.51452191 12.8031804  12.27019776]
 [18.46375142 13.53967468  0.         11.9261086  10.33819861]]
